### ISSUE TITLE
Returning required module

### ISSUE THREAD

**Issue by ruimarinho** [JerrySievert/plv8-modules#1]
Currently, only some specific modules are being returned by the require method. I assume the exports object is being modified by reference inside the required module. However, this fails short for more complex modules such as lodash which deal with a multitude of environments.

What can be done in these scenarios?

**Comment by JerrySievert** [comment]
i'm going to have to look into the lodash scenario, and get back to you.

in addition, i'm working in parallel on a good test harness for testing things inside of postgres, based on some code i wrote to help test another project: https://github.com/JerrySievert/mongolike/tree/master/test

i had started adding this to `plv8-modules` itself, but realized that it should be broken out and released.

any thoughts on that? (not on github yet)

**Comment by ruimarinho** [comment]
Ok, great -- I was genuinely intrigued by how you found a way to test plv8-modules inside the current repo :) I'll take a closer look soon.

What would be the best way to debug a module's code? I'd like to understand why lodash is not taking the correct decision when exporting. Is `this.elog` available?

**Comment by JerrySievert** [comment]
`plv8.log()` should be available, and i alias `plv8.console` - if you add:

```
var console = plv8.console;
```

to here: https://github.com/JerrySievert/plv8-modules/blob/master/sql/001-startup.sql#L10

it should allow you to use `console.log()`.

if you're up for it, i would love some help on this project

**Comment by ruimarinho** [comment]
I am definitely interested in helping! I'll give that a try to see if I can debug why lodash is not attaching correctly. Were you able to get exports populated with the Cromag module?

**Comment by JerrySievert** [comment]
yes, and was able to:

```
[local] jerry@jerry=# DO $$ var cromag = plv8.require('cromag'); var d = new cromag(); plv8.console.log(d.toString()); $$ LANGUAGE plv8;
NOTICE:  00000: SELECT code FROM commonjs.plv8_modules WHERE module = $1
LOCATION:  plv8_Elog, plv8_func.cc:347
NOTICE:  00000: Tue Mar 29 2016 14:18:39 GMT-0700 (PDT)
LOCATION:  plv8_Elog, plv8_func.cc:347
DO
Time: 139.873 ms
```

i just remembered that i modified cromag locally to work (hacked it up).

see: https://gist.github.com/JerrySievert/26c64ef68c71ab85ff9932532c5d7dae

sorry - just remembered i had to do that

**Comment by JerrySievert** [comment]
i gave you access to the repo, i just ask that we both go the pull request model (going to have to enforce that on myself) for the time being!

**Comment by ruimarinho** [comment]
Got it, no worries. I'll see if I can dig deeper into this as I'm not
completely aware of what context plv8 passes on to the module.

Is there any better alternative to eval? E.g. new Function('code').

On Tuesday, March 29, 2016, Jerry Sievert notifications@github.com wrote:

> yes, and was able to:
> 
> [local] jerry@jerry=# DO $$ var cromag = plv8.require('cromag'); var d = new cromag(); plv8.console.log(d.toString()); $$ LANGUAGE plv8;
> NOTICE:  00000: SELECT code FROM commonjs.plv8_modules WHERE module = $1
> LOCATION:  plv8_Elog, plv8_func.cc:347
> NOTICE:  00000: Tue Mar 29 2016 14:18:39 GMT-0700 (PDT)
> LOCATION:  plv8_Elog, plv8_func.cc:347
> DO
> Time: 139.873 ms
> 
> i just remembered that i modified cromag locally to work (hacked it up).
> 
> see: https://gist.github.com/JerrySievert/26c64ef68c71ab85ff9932532c5d7dae
> 
> sorry - just remembered i had to do that
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/JerrySievert/plv8-modules/issues/1#issuecomment-203110728

## 

## 

Rui Marinho

**Comment by JerrySievert** [comment]
there might be - i hate the idea of an eval, but wanted to make sure that the results ended up `exports`.

the current method makes it available by having `exports` in scope, but can be dangerous.

thinking about it, if that doesn't work, we can always extend `plv8` to have a safer eval:

```
var exports = exports;
run_in_sandbox(code, { exports: exports });
// module now exists in exports
```

ala https://nodejs.org/api/vm.html#vm_script_runinnewcontext_sandbox_options

**Comment by ruimarinho** [comment]
> i gave you access to the repo, i just ask that we both go the pull request model (going to have to enforce that on myself) for the time being!

Thanks! Just noticed it. Sure, I do it myself too ;)

Got some pretty nice advancements - just got lodash (CDN full build) to load cleanly without any changes. I guess any package will load after getting this one sorted out!

Missing some cleanup before I can get some working examples. I was able to mimic the vm of node.js by using the Function constructor, although it lacks the security of a proper sandbox - I did make the function run in strict mode which limits this issue considerably.

**Comment by JerrySievert** [comment]
that's an amazing feat - i can't wait to see it.  i will be traveling for most of the day tomorrow, so if i don't reply, that's why.

**Comment by ruimarinho** [comment]
Did some cleanup just so that I can share what's the current status:

``` sql
CREATE OR REPLACE FUNCTION commonjs.startup() RETURNS BOOLEAN AS
$$
  plv8._cache = {};

  plv8.require = function(name) {
    if (plv8._cache[name]) {
      return plv8._cache[name].exports;
    }

    var result = plv8.execute('SELECT code FROM commonjs.modules WHERE name = $1', [name]);

    if (result && result.length) {
      var exports = {};
      var module = {
        exports: exports
      };
      var console = plv8.console;

      new Function(['module', 'exports'], '"use strict";' + result[0].code)(module, exports);

      plv8._cache[name] = module;

      return module.exports;
    } else {
      var err = new Error('Cannot find module "' + name + '"');
      err.code = 'MODULE_NOT_FOUND';

      throw err;
    }
  }

  // Add console functionality.
  plv8.console = {
    log: function() {
      var len = arguments.length;
      var args = new Array(len);

      for(var i = 0; i < len; ++i) {
        args[i] = arguments[i];
      }

      plv8.elog(NOTICE, args.join(' '));
    },
    warn: function() {
      var len = arguments.length;
      var args = new Array(len);

      for(var i = 0; i < len; ++i) {
        args[i] = arguments[i];
      }

      plv8.elog(WARNING, args.join(' '));
    },
    error: function() {
      var len = arguments.length;
      var args = new Array(len);

      for(var i = 0; i < len; ++i) {
        args[i] = arguments[i];
      }

      plv8.elog(ERROR, args.join(' '));
    }
  };

  return true;
$$
LANGUAGE plv8 IMMUTABLE STRICT;
```

**Comment by JerrySievert** [comment]
great! when you're ready, would you mind creating a pull request?  i will do the same - we can code review each other and merge each other's requests.

i am currently working on getting the testing library in a working order - will try to get the repo created this evening (i am in PDT timezone, USA).

**Comment by ruimarinho** [comment]
Yep, we'll try to get it ready for review this week. I'm on GMT+1 so I guess I should get some sleep :) :+1: for the test suite.

**Comment by JerrySievert** [comment]
\o/

**Comment by JerrySievert** [comment]
ok, i've introduce equinox - https://www.npmjs.com/package/equinox

i'll start trying to port tests back to it, and get us something workable.

**Comment by ruimarinho** [comment]
That looks quite cool! I'll take a more deeper look soon.

In the meantime I have progressed with some testing regarding the usage of the example above. I think I'll be able to submit a PR here with mostly documentation improvements regarding module loading.

**Comment by erichanson** [comment]
Thought I would just bump this issue.  Is `plv8-modules` the current best practice for working with external libraries?

**Comment by JerrySievert** [comment]
it's not an official plv8 package, but it does work.

there had been a couple of others on npm, but a search isn't currently finding them for me.

**Comment by erichanson** [comment]
I found [es6-to-plv8](https://github.com/CSTARS/es6-to-plv8).

Would it be feasible to make es6's [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) work in plv8?  I know plv8 can't read from the filesystem, but is there something more clever we can do?  It seems like the world is moving towards es6 modules, and I'm working on a IDE that I would love to have play nice with the node universe, so choosing the most forward-thinking pattern here is important to me, just not sure what direction to go.

**Comment by JerrySievert** [comment]
you're welcome to open an issue on the plv8 repo - I haven't spent any time looking at how v8 implementers would implement import, but I could probably figure it out (or would welcome a PR).

if it gets implemented, it would be for 3.0, and not back ported into the older versions unless there were a PR for it.

what's stopped me in the past is that plv8 was staying fairly neutral in the module implementation discussions previously, hence this repo, but having `import` and an already breaking-change plv8 would be a good time to do it.

@pkit may have some pointers toward `import`

**Comment by pkit** [comment]
@erichanson I don't think that it's feasible. plv8 runs code in an isolate context. And `import` was created specifically for a module system. You can always babel/webpack/rollup it into something that is more useful for a running context. You need to treat plv8 like a browser environment, I don't think any browser supports or will ever support `import` natively but that doesn't prevent people from using import everywhere in `react`, for example. It's just webpacked into more browser-friendly code at the build step.

**Comment by erichanson** [comment]
Ok, I created [an issue](https://github.com/plv8/plv8/issues/341) on the main plv8 repo.

**Comment by JerrySievert** [comment]
I am responding on the other issue, I think that the isolated context issue can be solved, but am looking into the keyword itself.  the biggest issue is going to be permissions.

**Comment by micburks** [comment]
@pkit I'd just like to point out that `import` syntax is currently supported by **all** [evergreen browsers](https://caniuse.com/#feat=es6-module) and also in node with a [runtime flag](https://nodejs.org/api/esm.html#esm_enabling). Not saying it would be easy to support, just fyi.

**Comment by pkit** [comment]
@micburks the support is for <script> tag which is an ugly hack to load a module. Because still no modules from fs can be loaded. Conceptually the modules are tied to fs and tree-like storage. I don't like it :)

**Comment by micburks** [comment]
@pkit I probably could have explained the link I sent. The `type="module"` script attribute is exactly how you load a module since modules are different from scripts. Also, by *module*, I mean an es module, not a node package, to which I think you may be referring.

Opinions aside, I wouldn't call `<script type="module">` an ugly hack, considering this has been standardized and implemented ([1](https://developers.google.com/web/fundamentals/primers/modules), [2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), [3](https://jakearchibald.com/2017/es-modules-in-browsers/)).

**Comment by pkit** [comment]
@micburks the original post referred to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
Which is not the browser tag.

**Comment by JerrySievert** [comment]
this issue has gone well past its lifecycle, so I'm going to go ahead and close it given that there's an issue open on plv8 - that's a better place for this particular discussion.
